# File for Azure Piplelines CI Builds
    
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Java7:
        java.version: '1.7'
      Java8:
        java.version: '1.8'
      Java10:
        java.version: '1.10'
  steps:
  - template: azure-pipelines-common-steps.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Java7:
        java.version: '1.7'
      Java8:
        java.version: '1.8'
      Java10:
        java.version: '1.10'
  steps:
  - template: azure-pipelines-common-steps.yml

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Java7:
        java.version: '1.7'
      Java8:
        java.version: '1.8'
      Java10:
        java.version: '1.10'
  steps:
  # Mac image doesn't include ant by default so install it
  - script: brew install ant
    displayName: Install Ant
  - template: azure-pipelines-common-steps.yml
